[template]
  incoming-hooks = ["Storyblok"]

[template.environment]
  STORYBLOK_PREVIEW_TOKEN = "aFjN92IYZGoQNTrMu3EquQtt"
  STORYBLOK_PERSONAL_TOKEN = "h4bj1UlVy8fkWUVZHKtHBwtt-280447-tpRp365zy8yQgBUo8Fyb"
  STORYBLOK_SPACE_ID = "#328426"
  LOCALE = "de-AT"
  CURRENCY = "EUR"
  SITE_LANG = "de"

[build]
  command = "npm run build"
  publish = "dist"
